global:
  elasticsearch:
    enabled: true
  kibana:
    enabled: false   # kept it out because of it's hook 
  logstash: 
    enabled: true
  metricbeat: 
    enabled: true

elasticsearch:
  replicas: 1
  secret:
    password: elastic   # password for elastic user
  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 200
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5
  # antiAffinity: "soft"  # when we have single node
  minimumMasterNodes: 1 # if replica is 1, on multi node comment it 
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=30s" # if replica is 1, on multi node make it wait_for_status=green

beat:
  elasticsearch_host: elasticsearch-master

logstash:
  logstashConfig:
    logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.enabled: false
        xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

  extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password