global:
  elasticsearch:
    enabled: true

  kibana:
    enabled: false
  logstash: 
    enabled: false

elasticsearch:
  replicas: 1
  image: elasticsearch
  podAnnotations: 
      "helm.sh/hook": pre-install
  secret:
    password: elastic   # password for elastic user

beat:
  elasticsearch_host: elasticsearch-master.elk.svc.cluster.local