global:
  elasticsearch:
    enabled: true
  kibana:
    enabled: true
  logstash: 
    enabled: true
  metricbeat: 
    enabled: true

elasticsearch:
  replicas: 1
  podAnnotations: 
      "helm.sh/hook": pre-install
  secret:
    password: elastic   # password for elastic user

beat:
  elasticsearch_host: elasticsearch-master